### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'dict' and 'str' following example

### ISSUE THREAD

**Issue by cdeblois** [Mendeley/mendeley-api-python-example#2]
Modified domain only here and this is what i get: 

<pre>
@dev1: mendeley-api-python-example $> sudo python mendeley-example.py
 * Running on http://dev1.catalyticds.com:5000/
 * Restarting with reloader
172.29.255.14 - - [25/Nov/2014 22:02:30] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/usr/local/lib/python2.7/dist-packages/flask/sessions.py", line 326, in save_session
    val = self.get_signing_serializer(app).dumps(dict(session))
  File "/usr/local/lib/python2.7/dist-packages/itsdangerous.py", line 566, in dumps
    rv = self.make_signer(salt).sign(payload)
  File "/usr/local/lib/python2.7/dist-packages/itsdangerous.py", line 412, in sign
    return value + sep + self.get_signature(value)
  File "/usr/local/lib/python2.7/dist-packages/itsdangerous.py", line 347, in get_signature
    key = self.derive_key()
  File "/usr/local/lib/python2.7/dist-packages/itsdangerous.py", line 336, in derive_key
    mac = hmac.new(self.secret_key, digestmod=self.digest_method)
  File "/usr/lib/python2.7/hmac.py", line 133, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python2.7/hmac.py", line 71, in __init__
    key = key + chr(0) * (blocksize - len(key))
TypeError: unsupported operand type(s) for +: 'dict' and 'str'
172.29.255.14 - - [25/Nov/2014 22:02:30] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
172.29.255.14 - - [25/Nov/2014 22:02:30] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
172.29.255.14 - - [25/Nov/2014 22:02:30] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
172.29.255.14 - - [25/Nov/2014 22:02:30] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
172.29.255.14 - - [25/Nov/2014 22:02:31] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
172.29.255.14 - - [25/Nov/2014 22:02:31] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
172.29.255.14 - - [25/Nov/2014 22:02:31] "GET /?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
</pre>

**Comment by silpol** [comment]
@cdeblois could you expand a bit on what were the issues?
